### ISSUE TITLE
[castai-aks-init] add apiKeySecretRef option

### ISSUE THREAD

**Issue by jz-wilson** [castai/helm-charts#160]
Can you add apiKeySecretRef for aks-init instead of relying on the secret: `castai-cluster-controller`

**Comment by aldor007** [comment]
hi @jz-wilson we have released new version of castai-cluster-controller 0.38.0 which add `apiKeySecretRef` to `aks-init-data`

**Comment by jz-wilson** [comment]
Awesome thank you!
